# Generated by Django 5.2.3 on 2025-06-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='contnet',
            new_name='content',
        ),
    ]
